### ISSUE TITLE
Initial value of new Sum records is twice the expected value.

### ISSUE THREAD

**Issue by AlejoAsd** [marcoshuck/go-distributed#1]
https://github.com/marcoshuck/go-distributed/blob/c3d8745480eeff95a7cb6885480983de55b3cb87/challenge/pkg/db/sum.go#L10-L16

If a record is not found, then the `Sum.Total` record is initialized with `value`. However, right after the initialization, the sum's `Total` is increased by `value` again. This will cause initial `Sum` records to have twice the intended value.

**Comment by marcoshuck** [comment]
Thanks for raising this up!
